image:
  repository: everpeace/kube-openmpi
  tag: 0.5.3
  pullPolicy: IfNotPresent
  # pullSecrets:
  # - name: ""

kubectlImage:
  repository: everpeace/kubectl
  tag: 1.9.2
  pullPolicy: IfNotPresent

gitSyncImage:
  repository: gcr.io/google_containers/git-sync
  tag: v2.0.6
  pullPolicy: IfNotPresent

networkPolicy:
  enabled: false

sshGateway:
  enabled: false
  nodePort: 30220

sshKey:
  # id_rsa: |
  #   ...
  # id_rsa_pub: |
  #   ...

mpiMaster:
  autoUpdateHostfile:
    enabled: true
    updateEvery: 15
  securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  customScheduling:
    enabled: false
    schedulerName: ""
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # volumes:
  # volumeMounts:

mpiWorkers:
  num: 4
  securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  customScheduling:
    enabled: false
    schedulerName: ""
    podDisruptionBudget:
      enabled: false
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    #  gpu: 1
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    #  gpu: 1
  podManagementPolicy: Parallel
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # volumes:
  # volumeMounts:

appCodesToSync:
# - name: chainermn
#   gitRepo: https://github.com/chainer/chainermn.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /chainermn-examples
#   subPath: chainermn/examples
# - name: chainer
#   gitRepo: https://github.com/chainer/chainer.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /chainer-examples
#   subPath: chainer/examples
# - name: your-secret-repo
#   gitRepo: git@github.com:your-org/your-secret-repo.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /your-secret-repo
#   gitSecretName: git-sync-creds
